### ISSUE TITLE
Project  Configuration

### ISSUE THREAD

**Issue by bhautikbharadava** [Grommerce/grommerce-store#1]
**Is your feature request related to a problem? Please describe.**
Set up a project with following things:
- React
- Redux
- Next.js
- Node.js 
- Postgres.

**Comment by reeversedev** [comment]
I have created a Index page. Do you need more pages or should I close this issue then?

**Comment by bhautikbharadava** [comment]
No it will be okay. Just make sure that scss can run on the project.

**Comment by reeversedev** [comment]
Scss is running fine on our current parcel based configuration. So I think, I should close this issue now. If you still think that there's a need for further discussion then you can reopen this issue.
